name: Go Build
on: [ push, pull_request ]
permissions:
  checks: write

jobs:
  test-1_24:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      upload-results: true
      go-version: 1.24
  test-1_25:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      upload-results: true
      go-version: 1.25
  test-1_26:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      upload-results: true
      go-version: 1.26
  test-1_24-mock:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      working-dir: "./logmock"
      go-version: 1.24
  test-1_25-mock:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      working-dir: "./logmock"
      go-version: 1.25
  test-1_26-mock:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      working-dir: "./logmock"
      go-version: 1.26
  test-1_24-errorlogs:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      working-dir: "./errorlogs"
      upload-results: true
      go-version: 1.24
  test-1_25-errorlogs:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      working-dir: "./errorlogs"
      upload-results: true
      go-version: 1.25
  test-1_26-errorlogs:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      working-dir: "./errorlogs"
      upload-results: true
      go-version: 1.26
  lint:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-lint.yml@v1
    with:
      golangci-lint-version: v2.12.2
