name: Go Build
on: [ push, pull_request ]
permissions:
  checks: write

jobs:
  build-matrix:
    name: Build Matrix
    runs-on: ubuntu-latest
    outputs:
      go-versions: ${{ steps.define-go-versions.outputs.go-versions }}
      module-paths: ${{ steps.define-modules.outputs.module_paths }}
    steps:
      - id: define-go-versions
        run: echo 'go-versions=[ "1.24", "1.25", "1.26" ]' >> "$GITHUB_OUTPUT"
      - id: define-modules
        run: echo 'module_paths=[ "./", "./logmock", "./errorlogs" ]' >> "$GITHUB_OUTPUT"

  test:
    needs: build-matrix
    name: Test
    strategy:
      fail-fast: false
      matrix:
        go-version: ${{ fromJson(needs.build-matrix.outputs.go-versions) }}
        module-path: ${{ fromJson(needs.build-matrix.outputs.module-paths) }}
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-test.yml@v1
    with:
      check-name: Test Report (Go ${{ matrix.go-version }} / ${{ matrix.module-path }})
      upload-results: true
      go-version: ${{ matrix.go-version }}
      working-dir: ${{ matrix.module-path }}

  lint:
    uses: Siroshun09/gh-actions-workflows/.github/workflows/go-lint.yml@v1
    with:
      golangci-lint-version: v2.12.2
